name: Release

on:
  release:
    types: [published]

jobs:
  validate:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "theme"
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/rss-feed-list/rss-feed-list
          yarn install
          yarn build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/rss-feed-list/rss-feed-list/dist/rss-feed-list.js
          asset_name: rss-feed-list.js
          tag: ${{ github.ref }}
          overwrite: true
