name: Release

on:
  release:
    types: [published]

jobs:
  validate:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: HACS Validation
        uses: "hacs/action@main"
        with:
          category: "theme"

  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          yarn install
          yarn build

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          path: dist/
